
server:
  port: 8101
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mapper路径和实体对象路径
mybatis:
  #  Mapper文件存放的位置
  mapperLocations: classpath:mapper/**/*.xml
  #  实体类所在的包
  typeAliasesPackage: com.valvulas.fancky.model.entity

logging:
  #  path没起作用
  path: /log/
  file: log.log
#开发配置
spring:
  application:
    name: SpringBootProject
  thymeleaf:
  #      view:
  #        prefix: /
  #        suffix: .html
  #   #  html
  #     prefix: classpath:/templates/
  #      #图片
  #    resources:
  #      static-locations: classpath:/
  datasource:
    demo:
      #注意冒号有空格，多数据源是jdbcUrl，spring默认url
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      #
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 0
      maintenanceInterval: 60
      maxIdleTime: 60
    test:
      #注意冒号有空格
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      #
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 0
      maintenanceInterval: 60
      maxIdleTime: 60