server:
  port: 8101
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mapper路径和实体对象路径
mybatis:
  #  Mapper文件存放的位置
  mapperLocations: classpath:mapper/**/*.xml
  #  实体类所在的包
  typeAliasesPackage: com.valvulas.fancky.model.entity


logging:
  #  path没起作用
  path: /log/
  file: log.log
#开发配置
spring:
  application:
    name: SpringBootProject
  thymeleaf:
  #      view:
  #        prefix: /
  #        suffix: .html
  #   #  html
  #     prefix: classpath:/templates/
  #      #图片
  #    resources:
  #      static-locations: classpath:/
  datasource:
    demo:
      #注意冒号有空格，多数据源是jdbcUrl，spring默认url
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      #
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 0
      maintenanceInterval: 60
      maxIdleTime: 60
    test:
      #注意冒号有空格
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      #
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 0
      maintenanceInterval: 60
      maxIdleTime: 60

    #mysql 连接池8h自动断开配置
    #    #验证连接的有效性
    #    spring.datasource.test-while-idle=true
    #    #获取连接时候验证，会影响性能
    #    spring.datasource.test-on-borrow=true
    #    spring.datasource.validation-query=SELECT 1 FROM DUAL
    #    #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
    #    spring.datasource.time-between-eviction-runs-millis=300000
    #    #连接池空闲连接的有效时间 ，设置30分钟
    #    spring.datasource.min-evictable-idle-time-millis=1800000
    #  spring-boot默认连接池
    #  spring-boot中，根据以下3个优先级加载连接池
    #  1）如果classpath中有HikariCP，优先选择它
    #  2）如果Tomcat pooling 连接池可用，就会选择它
    #  3）如果以上都没有，则会选择Commons DBCP2连接池
    #    dbcp2:
    #      test-on-borrow: true
    #      validation-query: SELECT 1
    #      time-between-eviction-runs-millis: 300000
    #      min-evictable-idle-time-millis: 1800000
    #      test-while-idle: true
    # HikariCP： springboot2.0 默认的连接池。https://github.com/brettwooldridge/HikariCP
    #HikariCP  高并发性能优。mysql 8h 空闲断开连接可用quartz 调度定期select 1  。
    #产生此问题DB工作就不繁忙，性能要求不高。可以用上面dbcp2的配置，采取空闲查询策略。

    # Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: false
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

